---
- hosts: localhost
  tasks:
    - name: Creando el virtual machine scale set...
      azure_rm_virtualmachinescaleset:
        resource_group: "{{ resource_group }}"
        name: "{{ vmss_name }}"
        vm_size: "{{ vm_size_option }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ vmss_password }}"
        ssh_password_enabled: True
        capacity: "{{ vm_capacity }}"
        virtual_network_name: "{{ vmss_name_network }}"
        subnet_name: "{{ vmss_name_subnet }}"
        upgrade_policy: "{{ policy_var }}"
        tier: Standard
        managed_disk_type: Standard_LRS
        os_disk_caching: ReadWrite
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: "{{ sku_var }}"
          version: latest
          resource_group: "{{ resource_group }}"
        load_balancer: "{{ vmss_name_lb }}"
...
